[project]
name = "flasherd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "appdirs>=1.4.4",
    "cx-freeze>=8.5.3",
    "grpcio>=1.76.0",
    "platformdirs>=4.5.1",
    "protobuf>=6.33.5",
]
